version: "3"

tasks:
  dev:
    desc: Start development server
    cmds:
      - docker compose up -d
      - concurrently -c blue,red,green,yellow -n SRV,WEB,APP,ADMIN --kill-others "cd server && air" "cd web && yarn dev" "cd app && yarn start" "cd admin && yarn dev"
