version: "3"

tasks:
  dev:
    desc: Start development server
    cmds:
      - docker compose up -d
      - concurrently -c blue,red,green -n SRV,WEB,APP --kill-others "cd server && air" "cd web && yarn dev" "cd volunteer-app && yarn start"
