version: "3"

tasks:
  build:
    desc: Build the project
    cmds:
      - go build -o bin/wevolunteer cmd/cli/main.go
  run:
    desc: Run the project
    cmds:
      - go run cmd/cli/main.go

  docker-build:
    desc: Build and Push the Docker image
    cmds:
      - docker build -t metadonors/wevolunteers-api:staging .
      - docker push metadonors/wevolunteers-api:staging

  test:
    desc: Run tests
    cmds:
      - go test ./...
  clean:
    desc: Clean the project
    cmds:
      - rm -rf bin
