name: ADMIN | Build image (staging)

on:
  push:
    paths:
      - "admin/**"
      - ".github/workflows/*admin*"
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./admin
          push: true
          tags: metadonors/wevolunteers-admin:staging
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update service
        run: |
          curl -X POST ${{ secrets.ADMIN_STAGING_WEBHOOK }}
